notification icons
binwiederhier/ntfy pull request #365
Opened 2022-07-16 20:14 UTC by wunter8

2022-07-17 19:18 UTC, binwiederhier requested changes

2022-07-17 19:18 UTC, binwiederhier commented on server/server.go
> +	iconURLRegex     = regexp.MustCompile(`^https?://`)
i'd just rename this to urlRegex or something

2022-07-17 19:18 UTC, binwiederhier commented on client/client.go
> +	Size int64  `json:"size,omitempty"`
I don't see anywhere in the code where Size or Type are filled/populated. Or am I missing something? I would have made icon just a string.

2022-07-18 04:12 UTC, wunter8 commented
The tests all pass just fine on my computer. I don't think my code affects `TestServer_PublishTooRequests_ShortReplenish` at all

2022-08-19 01:06 UTC, binwiederhier approved these changes
This looks fantastic.

2022-09-11 20:32 UTC, merged