Document Matrix pushkey error + set log level to warnings for Matrix errors
binwiederhier/ntfy pull request #384
Opened 2022-08-19 10:01 UTC by christophehenry

The rationale is to clearly indicate what is set in the configuration compared to what was received in the request for debug purpose. Also, Matrix request errors now logs in warning level. I believe this can be disturbing having your setup not working and no error being logged in the default log level.

2022-08-19 14:23 UTC, binwiederhier requested changes
Looks great. Left a comment.

2022-08-21 15:03 UTC, christophehenry commented on server/server_matrix.go
> +	log.Warn("%s Matrix gateway error: %s", logHTTPPrefix(v, r), err.Error())
Sounds reasonnable.

2022-08-21 16:37 UTC, binwiederhier commented
Thanks

2022-08-21 16:37 UTC, merged

2022-08-21 16:53 UTC, binwiederhier commented
@christophehenry Could you fix the test please: https://github.com/binwiederhier/ntfy/runs/7940253761?check_suite_focus=true